### ISSUE TITLE
Remove Kokkos Makefile

### ISSUE THREAD

**Issue by tomdeakin** [UoB-HPC/BabelStream#110]
Kokkos [no longer supports building using Makefiles](https://github.com/kokkos/kokkos/issues/1394#issuecomment-963560374) - only CMake is supported.

**Comment by tom91136** [comment]
Do we want to also drop support for the remaining Makefiles?

**Comment by tomdeakin** [comment]
Yes, let's do this in v4.0 for everything.

**Comment by tomdeakin** [comment]
(All) Makefiles removed by #102.
