### ISSUE TITLE
Upgrade RAJA to 0.14.x

### ISSUE THREAD

**Issue by tom91136** [UoB-HPC/BabelStream#114]
RAJA 0.14.x contains about a years worth of changes (source incompatible) with additional backend support (SYCL).

**Comment by tomdeakin** [comment]
Should be resolved by 6945cbcec71be6ad09b2ea, pending https://github.com/LLNL/RAJA/issues/1296 and https://github.com/LLNL/RAJA/pull/1302

**Comment by tomdeakin** [comment]
@tom91136 - I saw there were some changes to the RAJA build system. Does this mean this is resolved, or are there API changes we need to update?

**Comment by tom91136** [comment]
Let me check if it still works with RAJA trunk.

**Comment by tom91136** [comment]
0.14.x works, minor fix required for >= [v2022.03.0](https://github.com/LLNL/RAJA/releases/tag/v2022.03.0), working on a patch now.

**Comment by tomdeakin** [comment]
Closed as merged
