### ISSUE TITLE
Add oneTBB as a FetchContent dependency

### ISSUE THREAD

**Issue by tom91136** [UoB-HPC/BabelStream#133]
oneTBB works well when used as a CMake FetchContent dependency.
By doing this, TBB and the benchmark can be configured and compiled together which allows TBB to make better decisions based on the environment (e.g. TBB uses hwloc for NUMA awareness, if available during configuration).

**Comment by tom91136** [comment]
See  https://github.com/UoB-HPC/cloverleaf_tbb/blob/23053cfc3d702bf289a07437577672f7f8fe7a9c/CMakeLists.txt#L9-L14 which integrates FetchContent TBB with CloverLeaf

**Comment by tomdeakin** [comment]
Done in a branch, will hit `develop` soon.
