### ISSUE TITLE
Always use the correct numeric type for all kernels

### ISSUE THREAD

**Issue by tom91136** [UoB-HPC/BabelStream#134]
There are several instances where the double constant `0.0` is used in a way that promotes everything it touches.
For example:
 https://github.com/UoB-HPC/BabelStream/blob/1d423fc70dd573b528ee43f521401277731b443a/src/std-data/STDDataStream.cpp#L85

In this case, the value is used on a templated function where the deducted type is based on that constant, so the kernel essentially gets fixed to double precision and not `T`.

There are several other models that does `T sum = 0.0;` which is probably OK. 
But for consistency I think we should probably be using aggregate initialisation for everything:

```cpp
std::transform_reduce(..., T{}); 
T sum{};  
```

**Comment by tomdeakin** [comment]
LGTM, apply this (with a comment in the code)
