### ISSUE TITLE
overflow in CUDA

### ISSUE THREAD

**Issue by jeffhammond** [UoB-HPC/BabelStream#136]
I kept getting 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Device does not have enough memory for all 3 buffers
```
when running with 1Gi elements on an A100-80GB.  It turned out that `3*ARRAY_SIZE*sizeof(T)` was computed to be 18446744065119617024, which is wrong.

I fixed it as follows:
```patch
diff --git a/src/cuda/CUDAStream.cu b/src/cuda/CUDAStream.cu
index b467d00..e1abe34 100644
--- a/src/cuda/CUDAStream.cu
+++ b/src/cuda/CUDAStream.cu
@@ -48,33 +48,37 @@ CUDAStream<T>::CUDAStream(const int ARRAY_SIZE, const int device_index)
   // Allocate the host array for partial sums for dot kernels
   sums = (T*)malloc(sizeof(T) * DOT_NUM_BLOCKS);

+  size_t array_bytes = sizeof(T);
+  array_bytes *= ARRAY_SIZE;
+  size_t total_bytes = array_bytes * 3;
+
   // Check buffers fit on the device
   cudaDeviceProp props;
   cudaGetDeviceProperties(&props, 0);
-  if (props.totalGlobalMem < 3*ARRAY_SIZE*sizeof(T))
+  if (props.totalGlobalMem < total_bytes)
     throw std::runtime_error("Device does not have enough memory for all 3 buffers");

   // Create device buffers
 #if defined(MANAGED)
-  cudaMallocManaged(&d_a, ARRAY_SIZE*sizeof(T));
+  cudaMallocManaged(&d_a, array_bytes);
   check_error();
-  cudaMallocManaged(&d_b, ARRAY_SIZE*sizeof(T));
+  cudaMallocManaged(&d_b, array_bytes);
   check_error();
-  cudaMallocManaged(&d_c, ARRAY_SIZE*sizeof(T));
+  cudaMallocManaged(&d_c, array_bytes);
   check_error();
   cudaMallocManaged(&d_sum, DOT_NUM_BLOCKS*sizeof(T));
   check_error();
 #elif defined(PAGEFAULT)
-  d_a = (T*)malloc(sizeof(T)*ARRAY_SIZE);
-  d_b = (T*)malloc(sizeof(T)*ARRAY_SIZE);
-  d_c = (T*)malloc(sizeof(T)*ARRAY_SIZE);
+  d_a = (T*)malloc(array_bytes);
+  d_b = (T*)malloc(array_bytes);
+  d_c = (T*)malloc(array_bytes);
   d_sum = (T*)malloc(sizeof(T)*DOT_NUM_BLOCKS);
 #else
-  cudaMalloc(&d_a, ARRAY_SIZE*sizeof(T));
+  cudaMalloc(&d_a, array_bytes);
   check_error();
-  cudaMalloc(&d_b, ARRAY_SIZE*sizeof(T));
+  cudaMalloc(&d_b, array_bytes);
   check_error();
-  cudaMalloc(&d_c, ARRAY_SIZE*sizeof(T));
+  cudaMalloc(&d_c, array_bytes);
   check_error();
   cudaMalloc(&d_sum, DOT_NUM_BLOCKS*sizeof(T));
   check_error();
```

I don't know if this is a compiler bug or C++ casting rules behaving as designed, but I'm more interested in solving the problem than understanding it.

**Comment by jeffhammond** [comment]
I saw this with NVC++ 22.7.  Haven't tried NVCC+GCC.

**Comment by tomdeakin** [comment]
Thanks Jeff - we started #127 to support larger inputs than an `int` can hold. There is definitely some weird type behaviour going on.

Thanks for sharing the fix for CUDA, I'll get it merged into that branch. BTW, we used `intptr_t` instead of `size_t`. We might need advice from a language expert on the difference/what should be used.

**Comment by tom91136** [comment]
Related: https://github.com/UoB-HPC/BabelStream/issues/123

**Comment by jeffhammond** [comment]
I though `size_t` was the type used for the maximum size possible array and the return type of `sizeof`, whereas `intptr_t` is specifically for casting pointers to and from integers, but in practica they are the same and I don't care what you choose to do 😄

**Comment by tom91136** [comment]
We probably need to update output padding as well, A100's bandwidth is getting close to breaking the formatting.

**Comment by jeffhammond** [comment]
9999999.999 MBytes/sec is safe for a few years.  Even 12-stacks of HBM3 won't exceed that.

**Comment by simonmcs** [comment]
Don’t forget you can use BabelStream to measure memory bandwidth to on-chip caches too…

Cheers,

Simo






--
Professor of High Performance Computing
PI for the Isambard GW4 Tier 2 HPC service
Head of the HPC Research Group, Department of Computer Science
University of Bristol, Merchant Venturers Building, Woodland Road, Clifton, Bristol, BS8 1UB, UK
Phone: +44 (0)117 455 0790, Twitter: @simonmcs, Web: http://uob-hpc.github.io/SimonMS/
HPC research webpage: http://uob-hpc.github.io<http://uob-hpc.github.io/>

________________________________

**Comment by tomdeakin** [comment]
@tom91136 can you apply this patch please?
