### ISSUE TITLE
error: identifier "__float128" is undefined

### ISSUE THREAD

**Issue by jeffhammond** [UoB-HPC/BabelStream#16]
I am posting this because others may encounter it and the solution should be logged for posterity.

# Problem

```
/opt/gcc/5.4.0/include/c++/5.4.0/type_traits(311): error: identifier "__float128" is undefined
```

# Solution 1
GCC 5.4.0 `include/c++/5.4.0/type_traits` needs to be modified to add ` && !defined(__CUDACC__)` in the following, which is at line 311 in my installation.
```
#if !defined(__STRICT_ANSI__) && defined(_GLIBCXX_USE_FLOAT128) && !defined(__CUDACC__)
  template<>
    struct __is_floating_point_helper<__float128>
    : public true_type { };
#endif
```

# Solution 2
Compile with strict ISO/ANSI flags (e.g. `-std=c++11` instead of the default `-std=gnu++11`) such that the GCC quadmath extensions will be disabled.

### Short error
```
nvcc fatal   : redefinition of argument 'std'
```

### Long error
```
/usr/bin/nvcc -M -D__CUDACC__ ~/Work/GPU/GPU-STREAM/CUDAStream.cu -o ~/Work/GPU/GPU-STREAM/build/CMakeFiles/gpu-stream-cuda.dir//gpu-stream-cuda_generated_CUDAStream.cu.o.NVCC-depend -ccbin /opt/gcc/5.4.0/bin/gcc-5.4 -m64 --std c++11 -Xcompiler ,\"-g\",\"-O3\",\"-fopenmp\",\"-fopenacc\",\"-Wall\",\"-Wextra\",\"-O3\",\"-DNDEBUG\" -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 --std=c++11 -DNVCC -I/usr/include -I~/Work/GPU/GPU-STREAM/build -I/usr/include
nvcc fatal   : redefinition of argument 'std'
```

# Related Work
Both Caffe and FFTW have identified the same issue with `nvcc`:
- https://github.com/BVLC/caffe/issues/3578
- https://github.com/FFTW/fftw3/issues/18

More detail can be found on [StackOverflow](http://stackoverflow.com/questions/34959032/nvcc-and-boost-1-60-error-identifier-float128-is-undefined).

**Comment by tomdeakin** [comment]
Are you able to check if this is still an issue with the new v3.1 build system. It looks like Solution 2 you presented sets the flags you need.

**Comment by tomdeakin** [comment]
Closing as Issue related to removed CMake build system.
