### ISSUE TITLE
A new name for GPU-STREAM

### ISSUE THREAD

**Issue by tomdeakin** [UoB-HPC/BabelStream#29]
GPU-STREAM is pretty ill-named now we have v3.0 running across CPUs, GPUs, Xeon Phi, etc. The different programming models also adds a different dimension to the supported hardware. As such, we should probably rename the project to something more accurate. Potential names are:

- X-STREAM
- Portable STREAM
- Parallel STREAM
- ManyCore STREAM

Thoughts/suggestions?

**Comment by psteinb** [comment]
_X-Stream_ is a bit too humble for my taste ;) what about `streamX` or any variant thereof.

**Comment by Ruyk** [comment]
Hetero-Stream ?

**Comment by tomdeakin** [comment]
XStream has a name clash with a Java library :-1:

**Comment by simonmcs** [comment]
All the single {X}-STREAM names seem to clash with something else.

Para-stream also clashes unfortunately (that would have been a good one).

There are two character versions which seem clean: MC-stream (for Many Core) is clean, Many-stream is quite clean too (though perhaps too much like just regular English to make it easy to Google for). Multi-stream also seems fairly clean (but regular English).

I'll keep thinking...

**Comment by psteinb** [comment]
What about srace as in "Stream Race" or Xmem like the cartoon ;)

**Comment by michaelboulton** [comment]
ETstream, like emerging technologies...also ET the extra terrestrial

**Comment by jrprice** [comment]
We've decided on BabelStream to highlight the 'many models' aspect with a geeky reference. Repository name, website, and links updated accordingly.

Thanks for all the input!
