### ISSUE TITLE
Bablestream is not working with HIP programming model on the latest ROCm1.7.1(1.7-137)

### ISSUE THREAD

**Issue by rkothako** [UoB-HPC/BabelStream#48]
Bablestream is not working with HIP programming model on the latest ROCm1.7.1(1.7-137).
Application should be modified as per the latest changes in HIP, correct?

Can you please take a look at below log and provide the resolution?

taccuser@ROCM-DTB-VG10:~/Desktop/BabelStream$ make -f HIP.make
/opt/rocm/hip/bin/hipcc -std=c++11 -DHIP main.cpp HIPStream.cpp -o hip-stream
HIPStream.cpp:129:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(copy_kernel), dim3(array_size/TBSIZE), ...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::copy' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float )] not viable: no overload
of 'copy_kernel' matching 'void ()(hip_impl::Empty_launch_parm, float *,
float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:162:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(add_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::add' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float *, float )] not viable: no
overload of 'add_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
float *, float *, float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:146:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(mul_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::mul' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float )] not viable: no overload
of 'mul_kernel' matching 'void ()(hip_impl::Empty_launch_parm, float *,
float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:179:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(triad_kernel), dim3(array_size/TBSIZE)...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::triad' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float *, float )] not viable: no
overload of 'triad_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
float *, float *, float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:213:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(dot_kernel), dim3(DOT_NUM_BLOCKS), dim3...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::dot' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float *, float , unsigned int>,
F = void ()(hip_impl::Empty_launch_parm, float *, float *, float ,
unsigned int)] not viable: no overload of 'dot_kernel' matching 'void
()(hip_impl::Empty_launch_parm, float *, float *, float *, unsigned int)'
for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:129:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(copy_kernel), dim3(array_size/TBSIZE), ...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::copy' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double )] not viable: no
overload of 'copy_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
double *, double *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:162:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(add_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::add' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double *, double )] not viable:
no overload of 'add_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
double *, double *, double *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:146:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(mul_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::mul' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double )] not viable: no
overload of 'mul_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
double *, double *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:179:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(triad_kernel), dim3(array_size/TBSIZE)...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::triad' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double *, double )] not viable:
no overload of 'triad_kernel' matching 'void
()(hip_impl::Empty_launch_parm, double *, double *, double *)' for 1st
argument
void hipLaunchKernel(
^
HIPStream.cpp:213:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(dot_kernel), dim3(DOT_NUM_BLOCKS), dim3...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::dot' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double *, double , unsigned
int>, F = void ()(hip_impl::Empty_launch_parm, double *, double *, double
, unsigned int)] not viable: no overload of 'dot_kernel' matching 'void
()(hip_impl::Empty_launch_parm, double *, double *, double *, unsigned
int)' for 1st argument
void hipLaunchKernel(
^
10 errors generated.
HIPStream.cpp:129:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(copy_kernel), dim3(array_size/TBSIZE), ...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::copy' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float )] not viable: no overload
of 'copy_kernel' matching 'void ()(hip_impl::Empty_launch_parm, float *,
float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:162:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(add_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::add' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float *, float )] not viable: no
overload of 'add_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
float *, float *, float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:146:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(mul_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::mul' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float )] not viable: no overload
of 'mul_kernel' matching 'void ()(hip_impl::Empty_launch_parm, float *,
float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:179:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(triad_kernel), dim3(array_size/TBSIZE)...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::triad' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float *, float >, F = void
()(hip_impl::Empty_launch_parm, float *, float *, float )] not viable: no
overload of 'triad_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
float *, float *, float *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:213:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(dot_kernel), dim3(DOT_NUM_BLOCKS), dim3...
^~~~~~~~~~~~~~~
HIPStream.cpp:270:16: note: in instantiation of member function
'HIPStream::dot' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <float *, float *, float , unsigned int>,
F = void ()(hip_impl::Empty_launch_parm, float *, float *, float ,
unsigned int)] not viable: no overload of 'dot_kernel' matching 'void
()(hip_impl::Empty_launch_parm, float *, float *, float *, unsigned int)'
for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:129:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(copy_kernel), dim3(array_size/TBSIZE), ...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::copy' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double )] not viable: no
overload of 'copy_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
double *, double *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:162:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(add_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::add' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double *, double )] not viable:
no overload of 'add_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
double *, double *, double *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:146:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(mul_kernel), dim3(array_size/TBSIZE), d...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::mul' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double )] not viable: no
overload of 'mul_kernel' matching 'void ()(hip_impl::Empty_launch_parm,
double *, double *)' for 1st argument
void hipLaunchKernel(
^
HIPStream.cpp:179:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(triad_kernel), dim3(array_size/TBSIZE)...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::triad' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double *, double >, F = void
()(hip_impl::Empty_launch_parm, double *, double *, double )] not viable:
no overload of 'triad_kernel' matching 'void
()(hip_impl::Empty_launch_parm, double *, double *, double *)' for 1st
argument
void hipLaunchKernel(
^
HIPStream.cpp:213:3: error: no matching function for call to 'hipLaunchKernel'
hipLaunchKernel(HIP_KERNEL_NAME(dot_kernel), dim3(DOT_NUM_BLOCKS), dim3...
^~~~~~~~~~~~~~~
HIPStream.cpp:271:16: note: in instantiation of member function
'HIPStream::dot' requested here
template class HIPStream;
^
/opt/rocm/hip/include/hip/hcc_detail/functional_grid_launch.hpp:142:6: note:
candidate function [with Args = <double *, double *, double , unsigned
int>, F = void ()(hip_impl::Empty_launch_parm, double *, double *, double
, unsigned int)] not viable: no overload of 'dot_kernel' matching 'void
()(hip_impl::Empty_launch_parm, double *, double *, double *, unsigned
int)' for 1st argument
void hipLaunchKernel(
^
10 errors generated.
Died at /opt/rocm/hip/bin/hipcc line 498.
HIP.make:7: recipe for target 'hip-stream' failed
make: *** [hip-stream] Error 1

**Comment by tomdeakin** [comment]
Thanks for reporting this. You mention that HIP has changed. If you’re happy to, do submit a pull request with the necessary changes for HIP.

**Comment by tomdeakin** [comment]
Fixed by the pull request #49
