### ISSUE TITLE
Add Julia and Rust versions

### ISSUE THREAD

**Issue by tomdeakin** [UoB-HPC/BabelStream#78]
These would be self-contained ports as not sure it's worth attempting plugging in these languages into the C++ main routine here.

**Comment by tom91136** [comment]
The story with Rust is quite interesting, Julia may have similar limitations by the looks of it.
Parallelism must be implemented using 3rd party libraries (crates);  [Rayon](https://docs.rs/rayon/1.5.0/rayon/) is the best candidate for our use case, resulting in semantically comparable kernels to the STD20 version.
If we implement it this way, performance will be tied to how well Rayon is optimised.

**Comment by tom91136** [comment]
Other than that, a draft PR for Rust should be ready sometime this week.

**Comment by tom91136** [comment]
@tomdeakin Currently Rust is blocked by not being NUMA aware although a fix might be coming soon (just waiting for Allocator API to make it into Rust stable) and the others like the Scala one are experimental. Should we have an unstable dir and put all of them there?

**Comment by tom91136** [comment]
@tomdeakin #95 is green, let's press the button :rocket:
