### ISSUE TITLE
ICE for RAJA on gcc 10.3.0  + CUDA

### ISSUE THREAD

**Issue by tom91136** [UoB-HPC/BabelStream#97]
This breaks CI runs for RAJA.
The ICE is tracked on [bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100102), let's revisit 2eca397 once this is fixed.

For reference, we also got a few nearly [identical](https://github.com/NVIDIA/nccl/issues/494) [ones](https://github.com/alpaka-group/alpaka/issues/1297).

**Comment by edrozenberg** [comment]
The GCC project has committed a patch:

https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=5357ab75dedef403b0eebf9277d61d1cbeb5898f
(in response to the problem report https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100102)

The patch removes ~ 40 lines from `gcc/cp/pt.c` and adds a couple of test cases.

The Nvidia stack works again for me after I built and installed patched gcc 10.3.0 packages.

**Comment by tom91136** [comment]
I'll check this again with the latest patches.

**Comment by tomdeakin** [comment]
@tom91136 to check!

**Comment by tom91136** [comment]
We've upgraded our CI  and bumped GCC to 12 now, RAJA+CUDA is now re-enabled without ICE.
