### ISSUE TITLE
number of devices are not consistent  

### ISSUE THREAD

**Issue by zjin-lcf** [UoB-HPC/BabelStream#99]
There are three devices:

```
Platform #0: Intel(R) FPGA Emulation Platform for OpenCL(TM)
 `-- Device #0: Intel(R) FPGA Emulation Device
Platform #1: Intel(R) OpenCL
 `-- Device #0: 11th Gen Intel(R) Core(TM) 
Platform #2: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) Iris(R) Xe Graphic
```

~/BabelStream/build$ ./sycl-stream --list

```
Devices:
0: Intel(R) FPGA Emulation Device
1: 11th Gen Intel(R) Core(TM) 
2: Intel(R) Iris(R) Xe Graphics
3: Intel(R) Iris(R) Xe Graphics
4: SYCL host device
```

Could you reproduce that ? 
Thanks

**Comment by tomdeakin** [comment]
Hi @zjin-lcf , thanks for sharing this. How are you producing the first list of devices, organised by platform?

BabelStream just uses a call to `cl::sycl::device::get_devices()` to get the list of devices.
The `--list` command list option just loops over the vector returned by that API call, printing out the names.
The number in BabelStream is just the index in that device vector we got from SYCL.

Can you share the start of the output from running this with the two Xe Graphics devices (`2` and `3`). The code prints out the Driver details before running. It's possible one of them is using OpenCL and the other is using Level Zero; both are viable backend options for Intel's SYCL implementation.

**Comment by tom91136** [comment]
I suspect your test environment has both the Level0 and OpenCL drivers installed.
You can verify this by running BabelStream with the two Xe Graphics device, the reported driver version and platform details should look slightly different. Would be great if you can also paste the output here so we can verify this.

If it is indeed L0 and CL, then the behaviour is documented (buried) in Intel's LLVM fork, on a page about [their Level0 plugin](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/LevelZeroBackend/LevelZeroBackend.md).

If you only want to see either the L0 or the CL device, try `export SYCL_DEVICE_FILTER=<level_zero|opencl>`, full documentation on what you can use is available [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/FilterSelector/FilterSelector.adoc).

**Comment by zjin-lcf** [comment]
Yes, both are installed. I will close the issue. Thank you for your explanation !
